name: exerciceSpring push workflow

on: push

jobs:
  premier-job:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Echo message Build OK
        run: echo "the build is ok"
