name: exerciceSpringBuild

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: ./mvnw install -DskipTests

      - name: Build the application
        run: ./mvnw package -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: target/Spring_Exercice_Etudiant-0.0.1-SNAPSHOT.jar

  download:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Récupérer l'artefact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact

      - name: Lister les fichiers
        run: ls
